# your informations
author:
  name: Venkatesh Iyer 
  description:
  picture: /assets/images/avatar.jpg
  favicon: /assets/images/favicon.png

# site description
description: Random. Completely Random. 

# site url
url: http://blog.venkateshiyer.net

# site title
title: Venkatesh Iyer

# site version
version: 0.0.1

# number of posts per page
paginate: 10

# your github username
github_username: rvenkatesh25

# set true to include or false to exclude share option
share:
  twitter: true
  facebook: true
  google_plus: true
  linkedin: true
  disqus: true

# if share.facebook is true, provide your facebook app id
facebook_app_id: 816004111874612

# if share.disqus is true, provide your disqus shortname, the api key and the number of comments to display
disqus_username: rvenkatesh25
disqus_api_key: suOtQXeyi8TJPpzjsCnZDs2N5GseV0oN172L3ht9el0DRkFh4ONZozbMQ8YkpkHf 
disqus_recent_comments_to_display: 5

markdown: kramdown
highlighter: rouge
exclude: [ 'README.md', 'src/', 'node_modules', 'bower_components', 'package.json', 'bower.json', 'Gruntfile.js' ]
excerpt_separator: <!--excerpt_separator-->
